main: de.dertoaster.ttespectatortp.TTESpectatorTPPlugin
name: ${NAME}
version: "${VERSION}"
api-version: "1.21.1"
author: DerToaster
description: Disables spectator mode AP and allows configuring a command to run instead
permissions:
  ttespectatortp.bypass:
    description: Bypass the functionality of this plugin
    default: OP
  ttespectatortp.allowspectatortp:
    description: Allows using spectator TP at all
    default: true
  ttespectatortp.*:
    description: Grants all other permissions
    default: false
    children:
      ttespectatortp.bypass: true
      ttespectatortp.allowspectatortp: true